new jobs to add weekly tag to stratum-bf images
stratum/stratum-ci pull request #31
Opened 2021-08-30 19:23 UTC by abhilashendurthi

2021-08-30 21:29 UTC, pudelkoM approved these changes

2021-08-31 04:59 UTC, Yi-Tseng requested changes

2021-08-31 04:59 UTC, Yi-Tseng commented on jjb/pipeline/stratum-bf-add-tag.groovy
> +	    stage('Push') {
Change all tabs to spaces

2021-09-09 19:25 UTC, Yi-Tseng approved these changes

2021-09-09 19:29 UTC, merged